#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""
embed_firmware.py — fetch the Realtek RTL8761BU Bluetooth firmware from
linux-firmware (if not already present) and generate RTLFirmwareData.hpp so the
blobs are compiled directly into the kext.

The firmware is NOT redistributed in this repo (Realtek's license); it is
downloaded at build time from kernel.org. Run automatically by `make`.
"""

import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "RTLFirmwareData.hpp"
RES = HERE / "Resources"
FW = RES / "rtl8761bu_fw.bin"
CFG = RES / "rtl8761bu_config.bin"

BASE = ("https://git.kernel.org/pub/scm/linux/kernel/git/firmware/"
        "linux-firmware.git/plain/rtl_bt/")


def fetch(path: Path) -> None:
    """Download a firmware file from linux-firmware if it isn't already here."""
    if path.exists() and path.stat().st_size > 0:
        return
    url = BASE + path.name
    print(f"  downloading {path.name} from linux-firmware…")
    RES.mkdir(exist_ok=True)
    try:
        with urllib.request.urlopen(url, timeout=60) as r:
            data = r.read()
    except Exception as e:  # noqa: BLE001
        sys.exit(f"ERROR: could not download {url}\n  {e}\n"
                 f"  Download it manually to {path} and re-run.")
    if not data:
        sys.exit(f"ERROR: downloaded {path.name} is empty.")
    path.write_bytes(data)
    print(f"    saved {len(data)} bytes")


def c_array(name: str, data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i:i + 16])
        lines.append(f"    {chunk},")
    body = "\n".join(lines)
    return (
        f"static const uint8_t {name}[] = {{\n{body}\n}};\n"
        f"static const uint32_t {name}Len = {len(data)};\n"
    )


def main() -> None:
    fetch(FW)
    fetch(CFG)

    fw = FW.read_bytes()
    cfg = CFG.read_bytes()

    if fw[:8] != b"Realtech":
        sys.exit(f"ERROR: {FW} has no 'Realtech' epatch signature — corrupt download?")
    if cfg[:4] != bytes([0x55, 0xAB, 0x23, 0x87]):
        sys.exit(f"ERROR: {CFG} has no Realtek config signature — corrupt download?")

    OUT.write_text(
        "// RTLFirmwareData.hpp — GENERATED by embed_firmware.py. Do not edit.\n"
        "// Firmware: linux-firmware rtl_bt/rtl8761bu_fw.bin + rtl8761bu_config.bin\n"
        "#pragma once\n\n"
        + c_array("kRtl8761buFw", fw)
        + "\n"
        + c_array("kRtl8761buConfig", cfg),
        encoding="utf-8",
    )
    print(f"Generated {OUT.name}: fw={len(fw)} bytes, config={len(cfg)} bytes")


if __name__ == "__main__":
    main()
